dashboard/src/account/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""pharos_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.urls import path

from account.views import (
    AccountSettingsView,
    JiraAuthenticatedView,
    JiraLoginView,
    JiraLogoutView,
    UserListView,
    account_resource_view,
    account_booking_view,
    account_images_view,
    account_configuration_view,
    account_detail_view,
    resource_delete_view,
    booking_cancel_view,
    image_delete_view,
    configuration_delete_view
)

app_name = "account"
urlpatterns = [
    url(r'^settings/', AccountSettingsView.as_view(), name='settings'),
    url(r'^authenticated/$', JiraAuthenticatedView.as_view(), name='authenticated'),
    url(r'^login/$', JiraLoginView.as_view(), name='login'),
    url(r'^logout/$', JiraLogoutView.as_view(), name='logout'),
    url(r'^users/$', UserListView.as_view(), name='users'),
    url(r'^my/resources/$', account_resource_view, name="my-resources"),
    path('my/resources/delete/<int:resource_id>', resource_delete_view),
    url(r'^my/bookings/$', account_booking_view, name="my-bookings"),
    path('my/bookings/cancel/<int:booking_id>', booking_cancel_view),
    url(r'^my/images/$', account_images_view, name="my-images"),
    path('my/images/delete/<int:image_id>', image_delete_view),
    url(r'^my/configurations/$', account_configuration_view, name="my-configurations"),
    path('my/configurations/delete/<int:config_id>', configuration_delete_view),
    url(r'^my/$', account_detail_view, name="my-account"),
]

dashboard/src/api/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""pharos_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.urls import path
from rest_framework import routers

from api.views import (
    BookingViewSet,
    UserViewSet,
    lab_profile,
    lab_status,
    lab_inventory,
    specific_job,
    specific_task,
    new_jobs,
    current_jobs,
    done_jobs,
    update_host_bmc,
    lab_host,
    get_pdf,
    get_idf,
    GenerateTokenView
)

router = routers.DefaultRouter()
router.register(r'bookings', BookingViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    path('labs/<slug:lab_name>/profile', lab_profile),
    path('labs/<slug:lab_name>/status', lab_status),
    path('labs/<slug:lab_name>/inventory', lab_inventory),
    path('labs/<slug:lab_name>/hosts/<slug:host_id>', lab_host),
    path('labs/<slug:lab_name>/hosts/<slug:host_id>/bmc', update_host_bmc),
    path('labs/<slug:lab_name>/booking/<int:booking_id>/pdf', get_pdf, name="get-pdf"),
    path('labs/<slug:lab_name>/booking/<int:booking_id>/idf', get_idf, name="get-idf"),
    path('labs/<slug:lab_name>/jobs/<int:job_id>', specific_job),
    path('labs/<slug:lab_name>/jobs/<int:job_id>/<slug:task_id>', specific_task),
    path('labs/<slug:lab_name>/jobs/new', new_jobs),
    path('labs/<slug:lab_name>/jobs/current', current_jobs),
    path('labs/<slug:lab_name>/jobs/done', done_jobs),
    url(r'^token$', GenerateTokenView.as_view(), name='generate_token'),
]

dashboard/src/booking/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""pharos_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from booking.views import (
    booking_detail_view,
    BookingDeleteView,
    bookingDelete,
    BookingListView,
    booking_stats_view,
    booking_stats_json,
    quick_create,
    booking_modify_image,
    booking_make_snapshot
)

app_name = "booking"
urlpatterns = [


    url(r'^detail/(?P<booking_id>[0-9]+)/$', booking_detail_view, name='detail'),
    url(r'^(?P<booking_id>[0-9]+)/$', booking_detail_view, name='booking_detail'),
    url(r'^delete/$', BookingDeleteView.as_view(), name='delete_prefix'),
    url(r'^delete/(?P<booking_id>[0-9]+)/$', BookingDeleteView.as_view(), name='delete'),
    url(r'^delete/(?P<booking_id>[0-9]+)/confirm/$', bookingDelete, name='delete_booking'),
    url(r'^modify/(?P<booking_id>[0-9]+)/image/$', booking_modify_image, name='modify_booking_image'),
    url(r'^modify/(?P<booking_id>[0-9]+)/snapshot/$', booking_make_snapshot, name='modify_make_snapshot'),
    url(r'^list/$', BookingListView.as_view(), name='list'),
    url(r'^stats/$', booking_stats_view, name='stats'),
    url(r'^stats/json$', booking_stats_json, name='stats_json'),
    url(r'^quick/$', quick_create, name='quick_create'),
]

dashboard/src/pharos_dashboard/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""pharos_dashboard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [

    url(r'^wf/', include('workflow.urls', namespace='workflow')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^resource/', include('resource_inventory.urls', namespace='resource')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls')),
    url(r'^messages/', include('notifier.urls', namespace='notifier'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/src/booking/models.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


from resource_inventory.models import ResourceBundle, ConfigBundle, OPNFVConfig
from account.models import Lab
from django.contrib.auth.models import User
from django.db import models
import resource_inventory.resource_manager


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, related_name='owner')
    collaborators = models.ManyToManyField(User, related_name='collaborators')
    start = models.DateTimeField()
    end = models.DateTimeField()
    reset = models.BooleanField(default=False)
    jira_issue_id = models.IntegerField(null=True, blank=True)
    jira_issue_status = models.CharField(max_length=50, blank=True)
    purpose = models.CharField(max_length=300, blank=False)
    ext_count = models.IntegerField(default=2)
    resource = models.ForeignKey(ResourceBundle, on_delete=models.SET_NULL, null=True)
    config_bundle = models.ForeignKey(ConfigBundle, on_delete=models.SET_NULL, null=True)
    opnfv_config = models.ForeignKey(OPNFVConfig, on_delete=models.SET_NULL, null=True)
    project = models.CharField(max_length=100, default="", blank=True, null=True)
    lab = models.ForeignKey(Lab, null=True, on_delete=models.SET_NULL)
    pdf = models.TextField(blank=True, default="")
    idf = models.TextField(blank=True, default="")

    class Meta:
        db_table = 'booking'

    def save(self, *args, **kwargs):
        """
        Save the booking if self.user is authorized and there is no overlapping booking.
        Raise PermissionError if the user is not authorized
        Raise ValueError if there is an overlapping booking
        """
        if self.start >= self.end:
            raise ValueError('Start date is after end date')
        # conflicts end after booking starts, and start before booking ends
        conflicting_dates = Booking.objects.filter(resource=self.resource).exclude(id=self.id)
        conflicting_dates = conflicting_dates.filter(end__gt=self.start)
        conflicting_dates = conflicting_dates.filter(start__lt=self.end)
        if conflicting_dates.count() > 0:
            raise ValueError('This booking overlaps with another booking')
        return super(Booking, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        res = self.resource
        self.resource = None
        self.save()
        resource_inventory.resource_manager.ResourceManager.getInstance().deleteResourceBundle(res)
        return super(self.__class__, self).delete(*args, **kwargs)

    def __str__(self):
        return str(self.purpose) + ' from ' + str(self.start) + ' until ' + str(self.end)

dashboard/src/booking/forms.py
##############################################################################
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
import django.forms as forms
from django.forms.widgets import NumberInput

from workflow.forms import (
    MultipleSelectFilterField,
    MultipleSelectFilterWidget,
    FormUtils)
from account.models import UserProfile
from resource_inventory.models import Image, Installer, Scenario
from workflow.forms import SearchableSelectMultipleField
from booking.lib import get_user_items, get_user_field_opts


class QuickBookingForm(forms.Form):
    purpose = forms.CharField(max_length=1000)
    project = forms.CharField(max_length=400)
    hostname = forms.CharField(max_length=400)

    installer = forms.ModelChoiceField(queryset=Installer.objects.all(), required=False)
    scenario = forms.ModelChoiceField(queryset=Scenario.objects.all(), required=False)

    def __init__(self, data=None, user=None, *args, **kwargs):
        if "default_user" in kwargs:
            default_user = kwargs.pop("default_user")
        else:
            default_user = "you"
        self.default_user = default_user

        super(QuickBookingForm, self).__init__(data=data, **kwargs)

        self.fields["image"] = forms.ModelChoiceField(
            Image.objects.filter(public=True) | Image.objects.filter(owner=user)
        )

        self.fields['users'] = SearchableSelectMultipleField(
            queryset=UserProfile.objects.select_related('user').exclude(user=user),
            items=get_user_items(exclude=user),
            required=False,
            **get_user_field_opts()
        )

        attrs = FormUtils.getLabData(0)
        self.fields['filter_field'] = MultipleSelectFilterField(widget=MultipleSelectFilterWidget(**attrs))
        self.fields['length'] = forms.IntegerField(
            widget=NumberInput(
                attrs={
                    "type": "range",
                    'min': "1",
                    "max": "21",
                    "value": "1"
                }
            )
        )

    def build_user_list(self):
        """
        returns a mapping of UserProfile ids to displayable objects expected by
        searchable multiple select widget
        """
        try:
            users = {}
            d_qset = UserProfile.objects.select_related('user').all().exclude(user__username=self.default_user)
            for userprofile in d_qset:
                user = {
                    'id': userprofile.user.id,
                    'expanded_name': userprofile.full_name,
                    'small_name': userprofile.user.username,
                    'string': userprofile.email_addr
                }

                users[userprofile.user.id] = user

            return users
        except Exception:
            pass

    def build_search_widget_attrs(self, chosen_users, default_user="you"):

        attrs = {
            'set': self.build_user_list(),
            'show_from_noentry': "false",
            'show_x_results': 10,
            'scrollable': "false",
            'selectable_limit': -1,
            'name': "users",
            'placeholder': "username",
            'initial': chosen_users,
            'edit': False
        }
        return attrs


class HostReImageForm(forms.Form):

    image_id = forms.IntegerField()
    host_id = forms.IntegerField()

dashboard/src/templates/booking/booking_calendar.html
{% extends "base.html" %}
{% load staticfiles %}

{% load bootstrap4 %}

{% block extrahead %}
    {{ block.super }}

    <link href="{% static "bower_components/fullcalendar/dist/fullcalendar.css" %}"
          rel='stylesheet'/>
    <link href="{% static "bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}"
          rel='stylesheet'/>
{% endblock extrahead %}

{% block content %}
    <div class="col-lg-8">
        <div class="container-fluid">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-calendar fa-fw"></i>Calendar
                </div>
                <div class="panel-body">
                    <div id='calendar'>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-edit fa-fw"></i>Booking
            </div>
            <div class="panel-body">
                {% if user.is_authenticated %}
                    <div id="booking_form_div">
                        {% bootstrap_form_errors form type='non_fields' %}
                        <form method="post" action="" class="form" id="bookingform">
                            {% csrf_token %}

                            <div class='input-group' id='starttimepicker'>
                                {% bootstrap_field form.start addon_after='<span class="glyphicon glyphicon-calendar"></span>' %}
                            </div>
                            <div class='input-group' id='endtimepicker'>
                                {% bootstrap_field form.end addon_after='<span class="glyphicon glyphicon-calendar"></span>' %}
                            </div>
                            {% bootstrap_field form.opsys %}
                            {% bootstrap_field form.purpose %}
                            {% bootstrap_field form.installer %}
                            {% bootstrap_field form.scenario %}
                            {% buttons %}
                                <button type="submit" class="btn btn btn-success">
                                    Book
                                </button>
                                <p>
                                    <br>By continuing, you agree to our
                                <a href="https://wiki.opnfv.org/display/INF/Lab-as-a-Service+at+the+UNH-IOL#Lab-as-a-ServiceattheUNH-IOL-AcceptableUsagePolicy">Acceptable Usage Policy</a>
                                </p>
                            {% endbuttons %}
                        </form>
                    </div>
                    <div id="booking_edit_form_div">
                        {% bootstrap_form_errors form type='non_fields' %}
                        <form method="post" action="" class="form" id="bookingeditform">
                            {% csrf_token %}
                            <div id='hide_if_noext'>
                            <div class='input-group' id='starttimeeditpicker'>
                                {% bootstrap_field form.start addon_after='<span class="glyphicon glyphicon-calendar"></span>' %}
                            </div>
                            <div class='input-group' id='endtimeeditpicker'>
                                {% bootstrap_field form.end addon_after='<span class="glyphicon glyphicon-calendar"></span>' %}
                            </div>
                            </div>
                            <script type="text/javascript">
                                if( {{ booking.ext_count }} <= 0 ){
                                    var hidediv = document.getElementById('hide_if_noext');
                                    hidediv.style.display = 'none';
                                    var par = document.createElement("div");
                                    var text = document.createTextNode("No Extensions Remaining");
                                    par.appendChild(text);
                                    par.style.fontWeight = 'bold';
                                    par.style.paddingBottom = '15pt';
                                    hidediv.parentNode.insertBefore(par,hidediv.nextSibling);
                                }
                            </script>
                            {% bootstrap_field form.opsys %}
                            {% bootstrap_field form.purpose %}
                            {% bootstrap_field form.installer %}
                            {% bootstrap_field form.scenario %}
                            {% bootstrap_field form.reset %}
                            {% buttons %}
                                <button type="submit" class="btn btn btn-success">
                                    Confirm Edit
                                </button>
                            {% endbuttons %}
                        </form>
                    </div>
                   <script type="text/javascript">
                    //Check if current view is an edit or a standard booking view
                    if(window.location.href.includes('edit')) {
                        var element = document.getElementById("bookingform");
                        element.parentNode.removeChild(element); }
                    else {
                        var element = document.getElementById("bookingeditform");
                        element.parentNode.removeChild(element); }
                    </script>
                {% else %}
                    <p>Please
                        <a href="{% url 'account:login' %}">
                            login with Jira</a>
                        to book this Pod</p>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="booking_detail_modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Booking Detail</h4>
                </div>
                <div class="modal-body" id="booking_detail_content">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close
                    </button>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

{% block extrajs %}
    <script type="text/javascript">
        var bookings_url = "{% url 'booking:bookings_json' resource_id=resource.id %}";
        var booking_detail_prefix = "{% url 'booking:detail_prefix' %}";
        var booking_delete_prefix = "{% url 'booking:delete_prefix' %}";
        var user_timezone = "{{ request.user.userprofile.timezone }}"
        {% autoescape off %}
        var sup_installer_dict = {{ installer_filter }}
        var sup_scenario_dict = {{ scenario_filter }}
        {% endautoescape %}

    </script>
    <script type="text/javascript">
    $(document).ready(function () {
        $("#id_installer").children().hide();
        $("#id_scenario").children().hide();
    });

    function installerHider() {
        dropFilter("id_installer", sup_installer_dict, "id_opsys");
        scenarioHider();
    }
    document.getElementById('id_opsys').addEventListener('change', installerHider);

    function scenarioHider() {
        dropFilter("id_scenario", sup_scenario_dict, "id_installer");
    }
    document.getElementById('id_installer').addEventListener('change', scenarioHider);

    function dropFilter(target, target_filter, master) {
        ob = document.getElementById(target);

        for(var i=0; i<ob.options.length; i++) {
            if ( ob.options[i].text == '---------' ) {
                ob.selectedIndex = i;
                }
        }

        targ_id = "#" + target;
        $(targ_id).children().hide();
        var drop = document.getElementById(master);
        var opts = target_filter[drop.options[drop.selectedIndex].value];
        if (!opts) {
            opts = {};
        }
        var emptyMap = {}

        var map = Object.create(null);
        for (var i = 0; i < opts.length; i++) {
            var j = opts[i];
            map[j] = true;
        }

        for (var i = 0; i < document.getElementById(target).childNodes.length; i++) {
            if (document.getElementById(target).childNodes[i].value in opts && !(document.getElementById(target).childNodes[i].value in emptyMap) ) {
                document.getElementById(target).childNodes[i].style.display = "inherit";
            }
        }
    }

    </script>
    <script src={% static "bower_components/moment/moment.js" %}></script>
    <script src={% static "bower_components/fullcalendar/dist/fullcalendar.js" %}></script>
    <script type="text/javascript"
            src={% static "bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}></script>
    <script src={% static "js/fullcalendar-options.js" %}></script>
    <script src={% static "js/datetimepicker-options.js" %}></script>
    <script src={% static "js/booking-calendar.js" %}></script>
{% endblock extrajs %}

dashboard/src/templates/booking/quick_deploy.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}

{% bootstrap_form_errors form type='non_fields' %}
<form id="quick_booking_form" action="/booking/quick/" method="POST" class="form">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 px-1 my-2">
                <div class="col py-2 rounded border">
                    <p>Please select a host type you wish to book. Only available types are shown.</p>
                    {% bootstrap_field form.filter_field show_label=False %}
                </div>
            </div>
            <div class="col-12 col-lg-3 px-1 my-2">
                <div class="col border rounded py-2 h-100">
                    {% bootstrap_field form.purpose %}
                    {% bootstrap_field form.project %}
                    {% bootstrap_field form.length %}
                    <span>Days: </span><output id="daysout">0</output>
                    <script>
                        document.getElementById("id_length").setAttribute("oninput", "daysout.value=this.value");
                        document.getElementById("daysout").value = document.getElementById("id_length").value;
                    </script>
                </div>
            </div>
            <div class="col-12 col-lg-3 px-1 my-2">
                <div class="col border rounded py-2 h-100">
                    <label>Collaborators</label>
                    {{ form.users }}
                </div>
            </div>
            <div class="col-12 col-lg-3 px-1 my-2">
                <div class="col border rounded py-2 h-100">
                    {% bootstrap_field form.hostname %}
                    {% bootstrap_field form.image %}
                </div>
            </div>
            <div class="col-12 col-lg-3 px-1 my-2">
                <div class="col border rounded py-2 h-100">
                    <strong>OPNFV: (Optional)</strong>
                    {% bootstrap_field form.installer %}
                    {% bootstrap_field form.scenario %}
                </div>
            </div>
            <div class="col-12 d-flex px-0 mt-2 justify-content-end">
                <button id="quick_booking_confirm" onclick="submit_form();" type="button" class="btn btn-success">Confirm</button>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    function submit_form()
    {
        //formats data for form submission
        multi_filter_widget.finish();
        // Submit the form manually since confirm button is type="button" now
        // due to the form submitting before the data was even created by finish()
        document.getElementById("quick_booking_form").submit();
    }

    function hide_dropdown(drop_id) {
        var drop = document.getElementById(drop_id);
        //select 'blank' option
        for( var i=0; i < drop.length; i++ )
        {
            if ( drop.options[i].text == '---------' )
                drop.selectedIndex = i;
        }
    }

    function get_selected_value(key){
        for( var attr in multi_filter_widget.result[key] ){
            if(!(attr in {}) )
                return attr;
        }
    }

    var sup_image_dict = {{image_filter | safe}};
    var sup_installer_dict = {{installer_filter | safe}};
    var sup_scenario_dict = {{scenario_filter | safe}};

    function imageHider() {
        var drop = document.getElementById("id_image");

        hide_dropdown("id_image");

        var lab_pk = get_selected_value("lab");
        var host_pk = get_selected_value("host");

        for (var i = 0; i < drop.childNodes.length; i++) {
            var image_object = sup_image_dict[drop.childNodes[i].value];
            if (image_object) //weed out empty option
            {
                if (image_object.host_profile == host_pk && image_object.lab == lab_pk) {
                    drop.childNodes[i].style.display = "inherit";
                    drop.childNodes[i].disabled = false;
                }
            }
        }
    }

    imageHider();
    $('#id_installer').children().hide();
    $('#id_scenario').children().hide();


    Array.from(document.getElementsByClassName("grid-item-select-btn")).forEach(function (element) {
        element.addEventListener('click', imageHider);
    });

    function installerHider() {
        dropFilter("id_installer", sup_installer_dict, "id_image");
        scenarioHider();
    }
    document.getElementById('id_image').addEventListener('change', installerHider);

    function scenarioHider() {
        dropFilter("id_scenario", sup_scenario_dict, "id_installer");
    }
    document.getElementById('id_installer').addEventListener('change', scenarioHider);

    function dropFilter(target, target_filter, master) {
        var dropdown = document.getElementById(target);

        hide_dropdown(target);

        var drop = document.getElementById(master);
        var opts = target_filter[drop.options[drop.selectedIndex].value];
        if (!opts) {
            opts = {};
        }

        var map = Object.create(null);
        for (var i = 0; i < opts.length; i++) {
            var j = opts[i];
            map[j] = true;
        }

        for (var i = 0; i < dropdown.childNodes.length; i++) {
            if (dropdown.childNodes[i].value in opts && !(dropdown.childNodes[i].value in {})) {
                dropdown.childNodes[i].style.display = "inherit";
                dropdown.childNodes[i].disabled = false;
            }
        }
    }
</script>
{% endblock %}